export interface JobEntryData{
    job:string,
    address:string,
    fee:number,
    contractDate: string,
    deliveredDate:string,
    feescollectedDate:string,
    feescollected: number,
    paymentTerms: string,
    expense: number,
    expenseTerms: string,
    subConductor: string,
    subConductorfee: number,
    modumfee: number,
    netfee: number,
    internalReview: string,
    marketing:string,
    marketingpercent: number,
    marketingfee:number,
    corporatepercent:number,
    corporatefee:number,
    productionpercent: number,
    productionfee:number,
    appraiser1:string,
    appraiser1percent: number,
    appraiser1fee:number,
    appraiser2:string,
    appraiser2percent: number,
    appraiser2fee:number,
    appraiser3:string,
    appraiser3percent: number,
    appraiser3fee:number,
    irpercent: number,
    irfee: number,
    totalPercent: number,
    hourlycharge: boolean
}